numberOfEpochs reduziert auf 3, batchSize erhöht auf 12;
baalIsBack/Datenanalyse-und-Daten-Mining pull request #22
Opened 2021-11-21 17:28 UTC by AnnaDobelmann

Laufzeit pro Epoch = 1m40s, Genauigkeit = 95%

2021-11-24 12:11 UTC, baalIsBack approved these changes

2021-11-24 12:13 UTC, baalIsBack requested changes
There are probably changes that are miissing in this branch and were not commited

2021-11-28 14:29 UTC, Julian-Christian approved these changes
Wow!

2021-11-28 14:30 UTC, baalIsBack approved these changes

2021-11-28 14:30 UTC, merged